// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Models;

#nullable disable

namespace Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251115002057_V1")]
    partial class V1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Server.Models.Racun", b =>
                {
                    b.Property<int>("RacunID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RacunID"));

                    b.Property<int?>("BrojStana")
                        .HasColumnType("int");

                    b.Property<bool>("JelPlacen")
                        .HasColumnType("bit");

                    b.Property<int>("MesecIzdavanja")
                        .HasColumnType("int");

                    b.Property<double>("RacunZaKomunalneUsluge")
                        .HasColumnType("float");

                    b.Property<double>("RacunZaStruju")
                        .HasColumnType("float");

                    b.Property<double>("RacunZaVodu")
                        .HasColumnType("float");

                    b.HasKey("RacunID");

                    b.HasIndex("BrojStana");

                    b.ToTable("Racuni");
                });

            modelBuilder.Entity("Server.Models.Stan", b =>
                {
                    b.Property<int>("BrojStana")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BrojStana"));

                    b.Property<int>("BrojClanova")
                        .HasColumnType("int");

                    b.Property<string>("ImeVlasnika")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("Kvadratura")
                        .HasColumnType("int");

                    b.HasKey("BrojStana");

                    b.ToTable("Stanovi");
                });

            modelBuilder.Entity("Server.Models.Racun", b =>
                {
                    b.HasOne("Server.Models.Stan", "ZaStan")
                        .WithMany("Racuni")
                        .HasForeignKey("BrojStana");

                    b.Navigation("ZaStan");
                });

            modelBuilder.Entity("Server.Models.Stan", b =>
                {
                    b.Navigation("Racuni");
                });
#pragma warning restore 612, 618
        }
    }
}
