// <auto-generated />
using System;
using BibliotekaBack.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BibliotekaBack.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20250909231555_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BibliotekaBack.Models.Book", b =>
                {
                    b.Property<int>("KnjigaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KnjigaID"));

                    b.Property<string>("EvidencioniBroj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GodinaIzdavanja")
                        .HasColumnType("int");

                    b.Property<string>("ImeAutora")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IzdataKnjiga")
                        .HasColumnType("bit");

                    b.Property<string>("Izdavac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naslov")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PripadaBiblioteciBibliotekaID")
                        .HasColumnType("int");

                    b.HasKey("KnjigaID");

                    b.HasIndex("PripadaBiblioteciBibliotekaID");

                    b.ToTable("Knjige");
                });

            modelBuilder.Entity("BibliotekaBack.Models.Library", b =>
                {
                    b.Property<int>("BibliotekaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BibliotekaID"));

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BibliotekaID");

                    b.ToTable("Biblioteke");
                });

            modelBuilder.Entity("BibliotekaBack.Models.RentedBook", b =>
                {
                    b.Property<int>("IzdavanjeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IzdavanjeID"));

                    b.Property<DateTime?>("DatumIzdavanja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatumVracanja")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IzBibliotekeBibliotekaID")
                        .HasColumnType("int");

                    b.Property<int?>("IzdataKnjigaKnjigaID")
                        .HasColumnType("int");

                    b.HasKey("IzdavanjeID");

                    b.HasIndex("IzBibliotekeBibliotekaID");

                    b.HasIndex("IzdataKnjigaKnjigaID");

                    b.ToTable("Izdavanja");
                });

            modelBuilder.Entity("BibliotekaBack.Models.Book", b =>
                {
                    b.HasOne("BibliotekaBack.Models.Library", "PripadaBiblioteci")
                        .WithMany("Knjige")
                        .HasForeignKey("PripadaBiblioteciBibliotekaID");

                    b.Navigation("PripadaBiblioteci");
                });

            modelBuilder.Entity("BibliotekaBack.Models.RentedBook", b =>
                {
                    b.HasOne("BibliotekaBack.Models.Library", "IzBiblioteke")
                        .WithMany("IzdateKnjige")
                        .HasForeignKey("IzBibliotekeBibliotekaID");

                    b.HasOne("BibliotekaBack.Models.Book", "IzdataKnjiga")
                        .WithMany()
                        .HasForeignKey("IzdataKnjigaKnjigaID");

                    b.Navigation("IzBiblioteke");

                    b.Navigation("IzdataKnjiga");
                });

            modelBuilder.Entity("BibliotekaBack.Models.Library", b =>
                {
                    b.Navigation("IzdateKnjige");

                    b.Navigation("Knjige");
                });
#pragma warning restore 612, 618
        }
    }
}
