// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Silosi.Server.Models;

#nullable disable

namespace Server.Migrations
{
    [DbContext(typeof(SilosiContext))]
    partial class SilosiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Silosi.Server.Models.Fabrika", b =>
                {
                    b.Property<int>("FabrikaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FabrikaID"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("FabrikaID");

                    b.ToTable("Fabrike");
                });

            modelBuilder.Entity("Silosi.Server.Models.Silos", b =>
                {
                    b.Property<int>("SilosID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SilosID"));

                    b.Property<int?>("FabrikaID")
                        .HasColumnType("int");

                    b.Property<int>("Kapacitet")
                        .HasColumnType("int");

                    b.Property<string>("Oznaka")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TrenutnoStanje")
                        .HasColumnType("int");

                    b.HasKey("SilosID");

                    b.HasIndex("FabrikaID");

                    b.ToTable("Silosi");
                });

            modelBuilder.Entity("Silosi.Server.Models.Silos", b =>
                {
                    b.HasOne("Silosi.Server.Models.Fabrika", "Fabrika")
                        .WithMany("Silosi")
                        .HasForeignKey("FabrikaID");

                    b.Navigation("Fabrika");
                });

            modelBuilder.Entity("Silosi.Server.Models.Fabrika", b =>
                {
                    b.Navigation("Silosi");
                });
#pragma warning restore 612, 618
        }
    }
}
