// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Models;

#nullable disable

namespace Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251116072644_V4")]
    partial class V4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Server.Models.Prodavnica", b =>
                {
                    b.Property<int>("ProdavnicaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProdavnicaID"));

                    b.Property<int>("BrojStolova")
                        .HasColumnType("int");

                    b.Property<string>("NazivProdavnice")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TrenutnoPopunjeniStolovi")
                        .HasColumnType("int");

                    b.HasKey("ProdavnicaID");

                    b.ToTable("Prodavnice");
                });

            modelBuilder.Entity("Server.Models.Sastojak", b =>
                {
                    b.Property<int>("SastojakID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SastojakID"));

                    b.Property<string>("BojaPrikaza")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("CenaSastojka")
                        .HasColumnType("float");

                    b.Property<int?>("DeoSendvicaSendvicID")
                        .HasColumnType("int");

                    b.Property<double>("InicijalnaDebljina")
                        .HasColumnType("float");

                    b.Property<double>("InicijalnaSirina")
                        .HasColumnType("float");

                    b.Property<int>("Kolicina")
                        .HasColumnType("int");

                    b.Property<string>("NazivSastojka")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("SastojakID");

                    b.HasIndex("DeoSendvicaSendvicID");

                    b.ToTable("Sastojci");
                });

            modelBuilder.Entity("Server.Models.Sendvic", b =>
                {
                    b.Property<int>("SendvicID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SendvicID"));

                    b.Property<double?>("CenaSendvica")
                        .HasColumnType("float");

                    b.Property<int?>("IzProdavniceProdavnicaID")
                        .HasColumnType("int");

                    b.HasKey("SendvicID");

                    b.HasIndex("IzProdavniceProdavnicaID");

                    b.ToTable("Sendvici");
                });

            modelBuilder.Entity("Server.Models.Sastojak", b =>
                {
                    b.HasOne("Server.Models.Sendvic", "DeoSendvica")
                        .WithMany("Sastojci")
                        .HasForeignKey("DeoSendvicaSendvicID");

                    b.Navigation("DeoSendvica");
                });

            modelBuilder.Entity("Server.Models.Sendvic", b =>
                {
                    b.HasOne("Server.Models.Prodavnica", "IzProdavnice")
                        .WithMany("Sendvici")
                        .HasForeignKey("IzProdavniceProdavnicaID");

                    b.Navigation("IzProdavnice");
                });

            modelBuilder.Entity("Server.Models.Prodavnica", b =>
                {
                    b.Navigation("Sendvici");
                });

            modelBuilder.Entity("Server.Models.Sendvic", b =>
                {
                    b.Navigation("Sastojci");
                });
#pragma warning restore 612, 618
        }
    }
}
