// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RentCarSistem.RentCarBack.Models;

#nullable disable

namespace RentCarBack.Migrations
{
    [DbContext(typeof(RentCarSistemContext))]
    [Migration("20250907204508_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RentCarSistem.RentCarBack.Models.Automobil", b =>
                {
                    b.Property<int>("AutomobilID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AutomobilID"));

                    b.Property<int>("BrojSedista")
                        .HasColumnType("int");

                    b.Property<int>("CenaPoDanu")
                        .HasColumnType("int");

                    b.Property<int>("Godiste")
                        .HasColumnType("int");

                    b.Property<bool>("JelIznajmljen")
                        .HasColumnType("bit");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PredjenaKilometraza")
                        .HasColumnType("int");

                    b.HasKey("AutomobilID");

                    b.ToTable("Automobili");
                });

            modelBuilder.Entity("RentCarSistem.RentCarBack.Models.Iznajmljivanje", b =>
                {
                    b.Property<int>("IznajmljivanjeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IznajmljivanjeID"));

                    b.Property<int>("BrojDana")
                        .HasColumnType("int");

                    b.Property<int?>("IznajmljeniAutoAutomobilID")
                        .HasColumnType("int");

                    b.Property<int?>("KorisnikAutaKorisnikID")
                        .HasColumnType("int");

                    b.HasKey("IznajmljivanjeID");

                    b.HasIndex("IznajmljeniAutoAutomobilID");

                    b.HasIndex("KorisnikAutaKorisnikID");

                    b.ToTable("Iznajmljivanja");
                });

            modelBuilder.Entity("RentCarSistem.RentCarBack.Models.Korisnik", b =>
                {
                    b.Property<int>("KorisnikID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KorisnikID"));

                    b.Property<string>("BrojVozacke")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("JMBG")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("PunoIme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KorisnikID");

                    b.ToTable("Korisnici");
                });

            modelBuilder.Entity("RentCarSistem.RentCarBack.Models.Iznajmljivanje", b =>
                {
                    b.HasOne("RentCarSistem.RentCarBack.Models.Automobil", "IznajmljeniAuto")
                        .WithMany()
                        .HasForeignKey("IznajmljeniAutoAutomobilID");

                    b.HasOne("RentCarSistem.RentCarBack.Models.Korisnik", "KorisnikAuta")
                        .WithMany()
                        .HasForeignKey("KorisnikAutaKorisnikID");

                    b.Navigation("IznajmljeniAuto");

                    b.Navigation("KorisnikAuta");
                });
#pragma warning restore 612, 618
        }
    }
}
